name: Megizen
authors: ['The DenizenScript Team', '0TickPulse']
version: 0.1.0-DEV (build ${BUILD_NUMBER})
main: net.tickmc.megizen.bukkit.Megizen
depend: [Denizen, ModelEngine]

api-version: '1.13'

softdepend: []
