name: Megizen
authors: ['The DenizenScript Team', '0TickPulse', 'heypr']
version: 0.27.1-DEV
main: net.tickmc.megizen.bukkit.Megizen
depend: [Denizen, ModelEngine]

api-version: '1.13'

softdepend: []
